lastupdatecheck: 0
recentrepos:
- /home/allen/.config/nvim
- /home/allen/Downloads/Q2TG
- /home/allen/MyNote
- /home/allen/git/config
- /home/allen/git
- /home/allen/Project/303
- /home/allen/Project/my_project
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
